name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "like parham-dev/genaiv1"
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure submodules are initialized and updated

      - name: Run Repository Cloning Script
        run: python3 scripts/install_custom_nodes.py

      - name: Validate custom_nodes Directory
        run: |
          custom_nodes_dir="ComfyUI/custom_nodes"
          if [ -d "$custom_nodes_dir" ]; then
            folder_count=$(find "$custom_nodes_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
            if [ "$folder_count" -le 3 ]; then
              echo "Error: Less than or equal to 3 folders found in $custom_nodes_dir."
              exit 1
            else
              echo "Validation passed: $folder_count folders found in $custom_nodes_dir."
            fi
          else
            echo "Error: Directory $custom_nodes_dir does not exist."
            exit 1
          fi

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
