name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "like parham-dev/genaiv1"
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout with Submodules
        uses: actions/checkout@v4
        # with:
        #   submodules: recursive # Ensure submodules are initialized and updated recursively

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
